In [18]:
#Imports
import pandas as pd
import numpy as np

In [19]:
# Sample of recipes
pd.set_option("display.max_columns", 30)
pd.set_option("display.width", 200)

In [20]:
# Check all columns and types
recipes = pd.read_csv("../data/raw/recipes.csv", nrows = 1000)
print(f"Shape: {recipes.shape}")
recipes.head()

Shape: (1000, 28)

,RecipeId,Name,AuthorId,AuthorName,CookTime,PrepTime,TotalTime,DatePublished,Description,Images,RecipeCategory,Keywords,RecipeIngredientQuantities,RecipeIngredientParts,AggregatedRating,ReviewCount,Calories,FatContent,SaturatedFatContent,CholesterolContent,SodiumContent,CarbohydrateContent,FiberContent,SugarContent,ProteinContent,RecipeServings,RecipeYield,RecipeInstructions
0,38,Low-Fat Berry Blue Frozen Dessert,1533,Dancer,PT24H,PT45M,PT24H45M,1999-08-09T21:46:00Z,Make and share this Low-Fat Berry Blue Frozen ...,"c(""https://img.sndimg.com/food/image/upload/w_...",Frozen Desserts,"c(""Dessert"", ""Low Protein"", ""Low Cholesterol"",...","c(""4"", ""1/4"", ""1"", ""1"")","c(""blueberries"", ""granulated sugar"", ""vanilla ...",4.5,4.0,170.9,2.5,1.3,8.0,29.8,37.1,3.6,30.2,3.2,4.0,NaN,"c(""Toss 2 cups berries with sugar."", ""Let stan..."
1,39,Biryani,1567,elly9812,PT25M,PT4H,PT4H25M,1999-08-29T13:12:00Z,Make and share this Biryani recipe from Food.com.,"c(""https://img.sndimg.com/food/image/upload/w_...",Chicken Breast,"c(""Chicken Thigh & Leg"", ""Chicken"", ""Poultry"",...","c(""1"", ""4"", ""2"", ""2"", ""8"", ""1/4"", ""8"", ""1/2"", ...","c(""saffron"", ""milk"", ""hot green chili peppers""...",3.0,1.0,1110.7,58.8,16.6,372.8,368.4,84.4,9.0,20.4,63.4,6.0,NaN,"c(""Soak saffron in warm milk for 5 minutes and..."
2,40,Best Lemonade,1566,Stephen Little,PT5M,PT30M,PT35M,1999-09-05T19:52:00Z,This is from one of my first Good House Keepi...,"c(""https://img.sndimg.com/food/image/upload/w_...",Beverages,"c(""Low Protein"", ""Low Cholesterol"", ""Healthy"",...","c(""1 1/2"", ""1"", NA, ""1 1/2"", NA, ""3/4"")","c(""sugar"", ""lemons, rind of"", ""lemon, zest of""...",4.5,10.0,311.1,0.2,0.0,0.0,1.8,81.5,0.4,77.2,0.3,4.0,NaN,"c(""Into a 1 quart Jar with tight fitting lid, ..."
3,41,Carina's Tofu-Vegetable Kebabs,1586,Cyclopz,PT20M,PT24H,PT24H20M,1999-09-03T14:54:00Z,This dish is best prepared a day in advance to...,"c(""https://img.sndimg.com/food/image/upload/w_...",Soy/Tofu,"c(""Beans"", ""Vegetable"", ""Low Cholesterol"", ""We...","c(""12"", ""1"", ""2"", ""1"", ""10"", ""1"", ""3"", ""2"", ""2...","c(""extra firm tofu"", ""eggplant"", ""zucchini"", ""...",4.5,2.0,536.1,24.0,3.8,0.0,1558.6,64.2,17.3,32.1,29.3,2.0,4 kebabs,"c(""Drain the tofu, carefully squeezing out exc..."
4,42,Cabbage Soup,1538,Duckie067,PT30M,PT20M,PT50M,1999-09-19T06:19:00Z,Make and share this Cabbage Soup recipe from F...,"""https://img.sndimg.com/food/image/upload/w_55...",Vegetable,"c(""Low Protein"", ""Vegan"", ""Low Cholesterol"", ""...","c(""46"", ""4"", ""1"", ""2"", ""1"")","c(""plain tomato juice"", ""cabbage"", ""onion"", ""c...",4.5,11.0,103.6,0.4,0.1,0.0,959.3,25.1,4.8,17.7,4.3,4.0,NaN,"c(""Mix everything together and bring to a boil..."

In [21]:
for col in recipes:
    null_count = recipes[col_name].isnull().sum()
    print(f" {col_name:.<40} {str(recipes[col].dtype):<15} nulls: {null_count}")

 RecipeId................................ int64           nulls: 0
 RecipeId................................ str             nulls: 0
 RecipeId................................ int64           nulls: 0
 RecipeId................................ str             nulls: 0
 RecipeId................................ str             nulls: 0
 RecipeId................................ str             nulls: 0
 RecipeId................................ str             nulls: 0
 RecipeId................................ str             nulls: 0
 RecipeId................................ str             nulls: 0
 RecipeId................................ str             nulls: 0
 RecipeId................................ str             nulls: 0
 RecipeId................................ str             nulls: 0
 RecipeId................................ str             nulls: 0
 RecipeId................................ str             nulls: 0
 RecipeId................................ float64         nulls: 0
 RecipeId................................ float64         nulls: 0
 RecipeId................................ float64         nulls: 0
 RecipeId................................ float64         nulls: 0
 RecipeId................................ float64         nulls: 0
 RecipeId................................ float64         nulls: 0
 RecipeId................................ float64         nulls: 0
 RecipeId................................ float64         nulls: 0
 RecipeId................................ float64         nulls: 0
 RecipeId................................ float64         nulls: 0
 RecipeId................................ float64         nulls: 0
 RecipeId................................ float64         nulls: 0
 RecipeId................................ str             nulls: 0
 RecipeId................................ str             nulls: 0

In [22]:
# Inspecting the messy columns
print("== RecipeIngredientParts ===")
for val in recipes["RecipeIngredientParts"].head(3):
    print(val)
    print()

print("=== Keywords ===")
for val in recipes["Keywords"].head(3):
    print(val)
    print()

print("=== RecipeInstructions ===")
for val in recipes["RecipeInstructions"].head(3):
    print(val)
    print()

== RecipeIngredientParts ===
c("blueberries", "granulated sugar", "vanilla yogurt", "lemon juice")

c("saffron", "milk", "hot green chili peppers", "onions", "garlic", "clove", "peppercorns", "cardamom seed", "cumin seed", "poppy seed", "mace", "cilantro", "mint leaf", "fresh lemon juice", "plain yogurt", "boneless chicken", "salt", "ghee", "onion", "tomatoes", "basmati rice", "long-grain rice", "raisins", "cashews", "eggs")

c("sugar", "lemons, rind of", "lemon, zest of", "fresh water", "fresh lemon juice")

=== Keywords ===
c("Dessert", "Low Protein", "Low Cholesterol", "Healthy", "Free Of...", "Summer", "Weeknight", "Freezer", "Easy")

c("Chicken Thigh & Leg", "Chicken", "Poultry", "Meat", "Asian", "Indian", "Weeknight", "Stove Top")

c("Low Protein", "Low Cholesterol", "Healthy", "Summer", "< 60 Mins")

=== RecipeInstructions ===
c("Toss 2 cups berries with sugar.", "Let stand for 45 minutes, stirring occasionally.", "Transfer berry-sugar mixture to food processor.", "Add yogurt and process until smooth.", "Strain through fine sieve. Pour into baking pan (or transfer to ice cream maker and process according to manufacturers' directions). Freeze uncovered until edges are solid but centre is soft.  Transfer to processor and blend until smooth again.", "Return to pan and freeze until edges are solid.", "Transfer to processor and blend until smooth again.",
"Fold in remaining 2 cups of blueberries.", "Pour into plastic mold and freeze overnight. Let soften slightly to serve.")

c("Soak saffron in warm milk for 5 minutes and puree in blender.", "Add chiles, onions, ginger, garlic, cloves, peppercorns, cardamom seeds, cinnamon, coriander and cumin seeds, poppy seeds, nutmeg, mace, cilantro or mint leaves and lemon juice. Blend into smooth paste. Put paste into large bowl, add yogurt and mix well.", "Marinate chicken in yogurt mixture with salt, covered for at least 2 - 6 hours in refrigerator.", "In skillet. heat oil over medium heat for 1 minute. Add ghee and 15 seconds later add onion and fry for about8 minutes.",
"Reserve for garnish.", "In same skillet, cook chicken with its marinade with tomatoes for about 10 minutes over medium heat, uncovered.", "Remove chicken pieces from the sauce and set aside. Add rice to sauce, bring to boil, and cook, covered over low heat for 15 minutes.", "Return chicken and add raisins, cashews and almonds; mix well.", "Simmer, covered for 5 minutes.", "Place chicken, eggs and rice in large serving dish in such a way that yellow of the eggs, the saffron-colored rice, the nuts and the chicken make a colorful display.",
"Add reserved onion as garnish.")

c("Into a 1 quart Jar with tight fitting lid, put sugar and lemon peel, or zest;  add 1 1/2 cups very hot water (not from tap!). With lid fitted firmly, shake jar until sugar is dissolved.", "Add lemon juice. Refrigerate until chilled.", "To Serve: Into each 12-ounce glass, over ice cubes, pour 1/4 cup of the lemon syrup.", "Then add chilled club soda or, if you prefer, water.", "Stir to mix well.")

In [23]:
nutrition_col = [
    "Calories", "FatContent", "SaturatedFatContent",
    "CholesterolContent","SodiumContent","CarbohydrateContent",
    "FiberContent", "SugarContent","ProteinContent"
]

for col in nutrition_col:
    null_count = recipes[col].isnull().sum()
    print(f"{col:.<30} type={recipes[col].dtype}, nulls={null_count}")

Calories...................... type=float64, nulls=0
FatContent.................... type=float64, nulls=0
SaturatedFatContent........... type=float64, nulls=0
CholesterolContent............ type=float64, nulls=0
SodiumContent................. type=float64, nulls=0
CarbohydrateContent........... type=float64, nulls=0
FiberContent.................. type=float64, nulls=0
SugarContent.................. type=float64, nulls=0
ProteinContent................ type=float64, nulls=0

In [24]:
print("=== Rating Distribution ===")
print(recipes["AggregatedRating"].describe())
print("\n=== RevirwCount ===")
print(recipes["ReviewCount"].describe())

=== Rating Distribution ===
count    806.000000
mean       4.478908
std        0.752752
min        1.000000
25%        4.000000
50%        5.000000
75%        5.000000
max        5.000000
Name: AggregatedRating, dtype: float64

=== RevirwCount ===
count    816.000000
mean      10.600490
std       31.168526
min        1.000000
25%        2.000000
50%        3.500000
75%        8.000000
max      609.000000
Name: ReviewCount, dtype: float64

In [25]:
print("=== Sample Times ===")
for col in ["CookTime", "PrepTime", "TotalTime"]:
    print(f"\n{col}:")
    print(recipes[col].head(5).tolist())

=== Sample Times ===

CookTime:
['PT24H', 'PT25M', 'PT5M', 'PT20M', 'PT30M']

PrepTime:
['PT45M', 'PT4H', 'PT30M', 'PT24H', 'PT20M']

TotalTime:
['PT24H45M', 'PT4H25M', 'PT35M', 'PT24H20M', 'PT50M']

In [26]:
reviews = pd.read_csv("../data/raw/reviews.csv")
print(f"Shape: {reviews.shape}")
reviews.head()

Shape: (1401982, 8)

   ReviewId  RecipeId  AuthorId        AuthorName  Rating                                             Review         DateSubmitted          DateModified
0         2       992      2008         gayg msft       5       better than any you can get at a restaurant!  2000-01-25T21:44:00Z  2000-01-25T21:44:00Z
1         7      4384      1634     Bill Hilbrich       4  I cut back on the mayo, and made up the differ...  2001-10-17T16:49:59Z  2001-10-17T16:49:59Z
2         9      4523      2046  Gay Gilmore ckpt       2  i think i did something wrong because i could ...  2000-02-25T09:00:00Z  2000-02-25T09:00:00Z
3        13      7435      1773     Malarkey Test       5  easily the best i have ever had.  juicy flavor...  2000-03-13T21:15:00Z  2000-03-13T21:15:00Z
4        14        44      2085        Tony Small       5                                 An excellent dish.  2000-03-28T12:51:00Z  2000-03-28T12:51:00Z

In [27]:
review_lengths = reviews["Review"].str.len()
print(f"Average review length: {review_lengths.mean():.0f} chars")
print(f"Min: {review_lengths.min()}, Max: {review_lengths.max()}")
print(f"Null reviews: {reviews['Review'].isnull().sum()}")

Average review length: 275 chars
Min: 1.0, Max: 8587.0
Null reviews: 214

In [28]:
print("=== Sample Reviews ===")
for val in reviews["Review"].head(3):
    print(f" {val[:100]}...")
    print()

=== Sample Reviews ===
 better than any you can get at a restaurant!...

 I cut back on the mayo, and made up the difference with sour cream to adjust the stiffness of the di...

 i think i did something wrong because i could taste the cornstarch in the finished product....

### Summary of Findings

1. Nested columns use R-style c ("a", "b") format - need parsing
2. Nutrition columns are Float64 with some nulls
3. Time columns are ISO 8601 strings (PT1H30M)
4. DataPublished is a string - needs datetime conversion
5. AggregatedRating has nulls (recipe with no reviews)
6. RecipeCategory and Keywords are string that need parsing
7. Images columns has R style arrays of URLs